steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backup-restore-app:$COMMIT_SHA'
      - '.'
      - '-f'
      - 'Dockerfile'
    id: Build

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/backup-restore-app:$COMMIT_SHA'
    id: Push

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backup-restore-app'
      - '--platform=managed'
      - '--image=gcr.io/$PROJECT_ID/backup-restore-app:$COMMIT_SHA'
      - '--region=us-central1'
      - '--set-env-vars=ALLOWED_ORIGINS=$_ALLOWED_ORIGINS,ALLOWED_EMAIL_DOMAIN=$_ALLOWED_EMAIL_DOMAIN'
      - '--update-secrets=OKTA_CLIENT_SECRET=okta-client-secret:latest'
      - '--quiet'
    id: Deploy

substitutions:
  _ALLOWED_ORIGINS: 'http://localhost:5173'
  _ALLOWED_EMAIL_DOMAIN: ''

images:
  - 'gcr.io/$PROJECT_ID/backup-restore-app:$COMMIT_SHA'
